# Generated by Django 5.1.15 on 2026-09-03 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room', models.CharField(blank=True, max_length=50)),
                ('book', models.CharField(blank=True, max_length=150)),
                ('subject', models.CharField(default='GEP', max_length=100)),
                ('total_class_days', models.PositiveIntegerField(default=20)),
            ],
            options={
                'ordering': ['term', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CommentBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Needs Improvement', 'Needs Improvement'), ('Attendance', 'Attendance'), ('Participation', 'Participation'), ('Homework', 'Homework'), ('Speaking', 'Speaking'), ('Reading', 'Reading'), ('Writing', 'Writing'), ('Listening', 'Listening'), ('Encouragement', 'Encouragement')], max_length=30)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Comment bank',
                'ordering': ['category', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ScoreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Quiz', 'Quiz'), ('Class Participation', 'Class Participation'), ('Homework', 'Homework'), ('Assignment', 'Assignment')], max_length=30, unique=True)),
                ('weight_percent', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Score categories',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('khmer_name', models.CharField(blank=True, max_length=150)),
                ('english_name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['student_code'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(default='GEP', max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='gep.classgroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='gep.studentprofile')),
            ],
            options={
                'ordering': ['class_group', 'student__student_code'],
                'unique_together': {('student', 'class_group')},
            },
        ),
        migrations.CreateModel(
            name='ScoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('max_points', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('date', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gep.scorecategory')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_items', to='gep.classgroup')),
            ],
            options={
                'ordering': ['category', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('english_name', models.CharField(max_length=150)),
                ('khmer_name', models.CharField(blank=True, max_length=150)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['teacher_id'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='gep.classgroup')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='gep.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'class_group')},
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='teachers', through='gep.TeacherAssignment', to='gep.classgroup'),
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='gep.academicyear')),
            ],
            options={
                'ordering': ['academic_year', 'order'],
                'unique_together': {('academic_year', 'name')},
            },
        ),
        migrations.AddField(
            model_name='classgroup',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='gep.term'),
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Tardy', 'Tardy'), ('Excused', 'Excused')], default='Present', max_length=10)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='gep.enrollment')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('enrollment', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('Midterm', 'Midterm'), ('Final', 'Final')], max_length=10)),
                ('listening', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('speaking', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('reading', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('writing', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='gep.enrollment')),
            ],
            options={
                'unique_together': {('enrollment', 'exam_type')},
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='gep.enrollment')),
                ('score_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='gep.scoreitem')),
            ],
            options={
                'unique_together': {('score_item', 'enrollment')},
            },
        ),
        migrations.CreateModel(
            name='ReportRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='gep.enrollment')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='gep.term')),
            ],
            options={
                'unique_together': {('enrollment', 'term')},
            },
        ),
    ]
